const WEBHOOK_URL="";
const $=id=>document.getElementById(id),V=id=>parseFloat($(id).value)||0,fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n),fK=n=>n.toLocaleString('fr-FR')+' km',qA=s=>document.querySelectorAll(s);
let carbI=1,cD=null,mAt=0;
function setMoto(e){qA('.moto-card').forEach(c=>c.classList.remove('active'));e.classList.add('active');const t=e.dataset.type,el=t==='electrique'||t==='eco-score',ph=t==='phev',hy=t==='hybride';$('consoUnit').textContent=el?'kWh/100km':'L/100km';$('prixUnit').textContent=el?'€/kWh':'€/L';$('conso').value=el?'25':ph?'4':hy?'5':'6';$('prix').value=el?'0.40':'1.70'}
function setAcq(e){qA('.acq-opt').forEach(c=>c.classList.remove('active'));e.classList.add('active');const a=e.dataset.acq,ci='<svg class="ico"><use href="#ico-card"/></svg> ';$('loyerLabel').innerHTML=ci+(a==='achat'?"Coût d'achat TTC <span class=\"tip\" data-t=\"Prix d'achat total TTC\">?</span>":a==='credit'?"Loyer crédit-bail annuel TTC <span class=\"tip\" data-t=\"Montant annuel crédit-bail TTC\">?</span>":"Loyer annuel TTC <span class=\"tip\" data-t=\"Loyer annuel TTC (LLD ou LOA)\">?</span>")}
function setFleet(e){qA('.fp').forEach(b=>b.classList.remove('active'));e.classList.add('active');$('flotte').value=e.dataset.v}
function syncFleetBtns(){const v=parseInt($('flotte').value)||1;qA('.fp').forEach(b=>b.classList.toggle('active',parseInt(b.dataset.v)===v))}
function toggleCarburant(){carbI=!carbI;$('toggleCarb').classList.toggle('on',carbI);$('carbHint').textContent=carbI?"Forfait à 67 % — l'énergie est incluse dans le calcul des avantages en nature":"Forfait à 50 % — l'énergie n'est pas incluse dans le calcul des avantages en nature"}
['fraisAssurance','fraisEntretien','fraisPneus'].forEach(id=>{$(id).addEventListener('input',()=>{$('fraisTotal').textContent=(V('fraisAssurance')+V('fraisEntretien')+V('fraisPneus')).toLocaleString('fr-FR')+' €/an'})});
function updateKm(){const t=parseInt($('kmTotal').value),p=Math.min(parseInt($('kmPerso').value),t);$('kmTotalVal').textContent=fK(t);$('kmPerso').max=t;$('kmPerso').value=p;$('kmPersoVal').textContent=fK(p);$('kmPersoMax').textContent=fK(t);const r=t>0?Math.round(p/t*100):0;$('kmPercPerso').textContent=r+'%';$('kmPercPro').textContent=(100-r)+'%'}
updateKm();
function runCalc(){const fr=V('fraisAssurance')+V('fraisEntretien')+V('fraisPneus'),p={l:V('loyer'),fr,co:V('conso'),px:V('prix'),kT:parseInt($('kmTotal').value),kP:parseInt($('kmPerso').value),tS:V('tauxSal')/100,tP:V('tauxPat')/100,tmi:parseFloat($('tmi').value)/100,fl:Math.max(1,parseInt($('flotte').value)||1),ci:carbI},r=p.kP/p.kT,nT=(p.kT*p.co/100)*p.px,nP=((p.kT-p.kP)*p.co/100)*p.px,nE=p.ci?nT:0;function sc(a,l,ne){const cs=a*p.tS,ir=a*p.tmi,v=l+p.fr+ne,cp=a*p.tP;return{aen:a,cS:cs,ir,tS:cs+ir,veh:v,cP:cp,tE:v+cp}}const aFF=p.ci?(p.l+p.fr+nP)*.67:(p.l+p.fr)*.5,aFR=p.ci?(p.l+p.fr+nT)*r:(p.l+p.fr)*r,nEl=(p.kT*25/100)*.4;cD={p,s:[sc(aFF,p.l,nE),sc(aFR,p.l,nE),sc((p.l+p.fr)*.5*.3,p.l,nEl),sc((p.l+p.fr)*r*.5,p.l,nEl)]}}
function onCalculate(){if(parseInt($('kmTotal').value)<=0)return;runCalc();const s=cD.s,fl=cD.p.fl,sv=((s[0].tS+s[0].tE)-(s[1].tS+s[1].tE))*fl;$('modalSavValue').textContent=fmt(Math.abs(sv));$('modalSavLabel').textContent=fl>1?`d'économies / an sur ${fl} véhicules`:`d'économies / an par véhicule`;mAt=Date.now();$('modal').classList.add('open');clE();setTimeout(()=>$('leadPrenom').focus(),150)}
function showResults(){const s=cD.s,fl=cD.p.fl,tF=s[0].tS+s[0].tE,tR=s[1].tS+s[1].tE,df=tF-tR;$('heroSav').textContent=fmt(df);$('heroFlotteLabel').textContent=fl>1?' par véhicule / an':' par an';const hft=$('heroFleetTotal');if(hft){if(fl>1){hft.textContent='Soit '+fmt(df*fl)+' pour '+fl+' véhicules';hft.style.display='block'}else{hft.style.display='none'}}$('heroForf').textContent=fmt(tF);$('heroReel').textContent=fmt(tR);$('heroArrow').textContent=(df>=0?'−':'+')+fmt(Math.abs(df)).replace(/[^\d\s]/g,'').trim()+' €';const mp={aen:'aen',cS:'cs',ir:'ir',tS:'ts',veh:'veh',cP:'cp',tE:'te'},fi=(pre,d)=>{for(let k in mp)$(pre+'_'+mp[k]).textContent=fmt(d[k])};fi('r_r',s[1]);fi('r_f',s[0]);fi('e_f',s[2]);fi('e_r',s[3]);const rw=[['Avantage en nature','aen'],['Charges salariales','cS'],['Impôt sur le revenu','ir'],['Coût total salarié','tS',1],['Coût véhicule + énergie','veh'],['Charges patronales','cP'],['Coût total employeur','tE',1]];let h='';rw.forEach(([lb,k,hl])=>{const vs=s.map(x=>x[k]),mn=Math.min(...vs);h+=`<tr${hl?' class="hl"':''}><td>${lb}</td>`;vs.forEach(v=>{h+=`<td${v===mn?' style="color:var(--success);font-weight:700"':''}>${fmt(v)}</td>`});h+='</tr>'});$('ftableBody').innerHTML=h;$('results').classList.add('visible');$('results').scrollIntoView({behavior:'smooth',block:'start'})}
const BD='mailinator.com yopmail.com yopmail.fr guerrillamail.com tempmail.com throwaway.email sharklasers.com grr.la dispostable.com maildrop.cc trashmail.com temp-mail.org fakeinbox.com tmpmail.net mohmal.com getnada.com discard.email jetable.org mytemp.email tempail.com burnermail.io meltmail.com mailsac.com'.split(' ');
const FD='gmail.com yahoo.com yahoo.fr hotmail.com hotmail.fr outlook.com outlook.fr live.com live.fr aol.com icloud.com me.com mail.com gmx.com gmx.fr protonmail.com proton.me zoho.com free.fr orange.fr wanadoo.fr laposte.net sfr.fr bbox.fr numericable.fr'.split(' ');
const TP=[/^test/i,/^fake/i,/^demo/i,/^abc$/i,/^aaa/i,/^xxx/i,/^zzz/i,/^qwer/i,/^asdf/i,/^azerty/i,/^toto/i,/^tutu/i,/^tata/i,/^foo$/i,/^bar$/i,/^null/i,/^none/i,/^admin$/i,/^blabla/i];
const NJ=[/^test$/i,/^fake$/i,/^demo$/i,/^abc$/i,/^aaa$/i,/^xxx$/i,/^zzz$/i,/^toto$/i,/^tata$/i,/^tutu$/i,/^foo$/i,/^bar$/i,/^null$/i,/^none$/i,/^na$/i,/^n\/a$/i,/^\.$/,/^-$/,/^\?$/,/^x$/i,/^qq$/i,/^azerty$/i,/^blabla$/i,/^fdp$/i];
function sE(id,m){const e=$(id);e.querySelector('span').textContent=m;e.classList.add('show');const i=e.previousElementSibling;if(i&&i.classList.contains('input'))i.classList.add('input-err')}
function clE(){qA('.field-err').forEach(e=>{e.classList.remove('show');const i=e.previousElementSibling;if(i&&i.classList.contains('input'))i.classList.remove('input-err')})}
function vL(){clE();let ok=1;const p=$('leadPrenom').value.trim(),n=$('leadNom').value.trim(),em=$('leadEmail').value.trim().toLowerCase(),en=$('leadEntreprise').value.trim();if($('leadWebsite').value.trim())return 0;if(Date.now()-mAt<2e3)return 0;if(!p){sE('errPrenom','Prénom requis');ok=0}else if(p.length<2){sE('errPrenom','Prénom trop court');ok=0}else if(NJ.some(r=>r.test(p))){sE('errPrenom','Prénom invalide');ok=0}else if(/\d/.test(p)){sE('errPrenom','Pas de chiffres');ok=0}
if(!n){sE('errNom','Nom requis');ok=0}else if(n.length<2){sE('errNom','Nom trop court');ok=0}else if(NJ.some(r=>r.test(n))){sE('errNom','Nom invalide');ok=0}else if(/\d/.test(n)){sE('errNom','Pas de chiffres');ok=0}
if(!em){sE('errEmail','Email requis');ok=0}else if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(em)){sE('errEmail','Email invalide');ok=0}else{const d=em.split('@')[1],l=em.split('@')[0];if(BD.includes(d)){sE('errEmail','Email jetable interdit');ok=0}else if(FD.includes(d)){sE('errEmail','Utilisez votre email pro');ok=0}else if(TP.some(r=>r.test(l))){sE('errEmail','Email invalide');ok=0}else if(d.length<4||!d.includes('.')){sE('errEmail','Domaine invalide');ok=0}}
if(!en){sE('errEntreprise','Entreprise requise');ok=0}else if(en.length<2){sE('errEntreprise','Nom trop court');ok=0}else if(NJ.some(r=>r.test(en))){sE('errEntreprise','Nom invalide');ok=0}
return ok}
function closeModal(){$('modal').classList.remove('open')}
function submitLead(){if(!vL())return;const b=$('btnSubmit');b.disabled=1;b.innerHTML='<span style="display:inline-block;width:16px;height:16px;border:2px solid rgba(255,255,255,.3);border-top-color:#fff;border-radius:50%;animation:spin .6s linear infinite"></span> Envoi…';const fl=parseInt($('flotte').value)||1,kT=parseInt($('kmTotal').value),kP=parseInt($('kmPerso').value),s=cD.s,pay={prenom:$('leadPrenom').value.trim(),nom:$('leadNom').value.trim(),email:$('leadEmail').value.trim().toLowerCase(),entreprise:$('leadEntreprise').value.trim(),telephone:$('leadTel').value.trim(),nombre_vehicules:fl,timestamp:new Date().toISOString(),source:'simulateur-aen',motorisation:document.querySelector('.moto-card.active')?.dataset.type,acquisition:document.querySelector('.acq-opt.active')?.dataset.acq||'lld',loyer:V('loyer'),conso:V('conso'),prix_carburant:V('prix'),carburant_inclus:carbI,assurance:V('fraisAssurance'),entretien:V('fraisEntretien'),pneumatiques:V('fraisPneus'),km_total:kT,km_perso:kP,pct_perso:Math.round(kP/kT*100),taux_sal:$('tauxSal').value+'%',taux_pat:$('tauxPat').value+'%',tmi:$('tmi').value+'%',eco_vehicule:Math.round((s[0].tS+s[0].tE)-(s[1].tS+s[1].tE)),eco_flotte:Math.round(((s[0].tS+s[0].tE)-(s[1].tS+s[1].tE))*fl),aen_forfait:Math.round(s[0].aen),aen_reel:Math.round(s[1].aen)};if(WEBHOOK_URL)fetch(WEBHOOK_URL,{method:'POST',body:JSON.stringify(pay)}).catch(()=>{});setTimeout(()=>{b.disabled=0;b.innerHTML='Résultats détaillés <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M5 12h14M12 5l7 7-7 7"/></svg>';closeModal();showResults()},800)}
function skipLead(){closeModal();showResults()}
['leadPrenom','leadNom','leadEmail','leadEntreprise'].forEach(id=>{$(id).addEventListener('input',()=>{const e='err'+id.charAt(4).toUpperCase()+id.slice(5);if($(e)){$(e).classList.remove('show');$(id).classList.remove('input-err')}})});
function updateFiscalHint(){document.querySelector('.ft-hint').textContent=`— Cot. sal. ${$('tauxSal').value}% · Cot. pat. ${$('tauxPat').value}% · TMI ${$('tmi').value}%`}
function toggleElec(){$('elecContent').classList.toggle('open');$('elecToggle').classList.toggle('open')}
function toggleTable(){const c=$('fullTable'),t=$('tableToggle'),o=c.classList.toggle('open');t.classList.toggle('open',o);t.innerHTML=o?'Masquer':'Tableau des 4 scénarios'}
function newSim(){['results','elecContent','elecToggle','fullTable','tableToggle'].forEach(id=>$(id).classList.remove('visible','open'));window.scrollTo({top:0,behavior:'smooth'})}
